version: "3.7"
services:
  db:
    # docker run --name postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=reddit-ish -v pgdata:/var/lib/postgresql/data -p 5432:5432 -d postgres:alpine
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reddit-ish
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # network_mode: bridge

  redis:
    # docker run --name redis -v redisdata:/redisdata -p 6379:6379 -d redis:alpine
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    # network_mode: bridge

  app-backend:
    image: sjlevalley/reddit-ish-server
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    # network_mode: bridge
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  redisdata:
  # app-frontend:
  #   image: reddit-ish-web
  #   ports:
  #     - "3000:3000"
  #   # network_mode: bridge
  #   depends_on:
  #     - db
  #     - cache
  #     - app-backend
